import { NextRequest, NextResponse } from 'next/server';
import { currentUser } from '@clerk/nextjs/server';
import { supabaseAdmin } from '@/lib/supabase';

export const dynamic = 'force-dynamic';

// ─── GET /api/candidate/profile ───────────────────────────────────────────────
// Load the signed-in candidate's saved profile from Supabase
export async function GET() {
  try {
      const user = await currentUser();
          if (!user) {
                return NextResponse.json({ error: 'Unauthorised' }, { status: 401 });
                    }

                        const { data, error } = await supabaseAdmin
                              .from('candidates')
                                    .select('*')
                                          .eq('clerk_user_id', user.id)
                                                .single();

                                                    // PGRST116 = no rows found — first login, profile not created yet
                                                        if (error && error.code !== 'PGRST116') {
                                                              console.error('Supabase GET error:', error);
                                                                    return NextResponse.json({ error: error.message }, { status: 500 });
                                                                        }

                                                                            return NextResponse.json(data || null);
                                                                              } catch (err) {
                                                                                  console.error('Profile GET error:', err);
                                                                                      return NextResponse.json({ error: String(err) }, { status: 500 });
                                                                                        }
                                                                                        }

                                                                                        // ─── POST /api/candidate/profile ──────────────────────────────────────────────
                                                                                        // Create or update the signed-in candidate's profile in Supabase
                                                                                        export async function POST(req: NextRequest) {
                                                                                          try {
                                                                                              const user = await currentUser();
                                                                                                  if (!user) {
                                                                                                        return NextResponse.json({ error: 'Unauthorised' }, { status: 401 });
                                                                                                            }

                                                                                                                const body = await req.json();
                                                                                                                    const email = user.emailAddresses[0]?.emailAddress ?? '';

                                                                                                                        // Calculate profile completion percentage (out of 7 key fields)
                                                                                                                            const completionFields = [
                                                                                                                                  body.title,
                                                                                                                                        body.experience,
                                                                                                                                              body.location,
                                                                                                                                                    body.specialisms?.length > 0,
                                                                                                                                                          body.bio,
                                                                                                                                                                body.currentCompany,
                                                                                                                                                                      body.certifications?.length > 0,
                                                                                                                                                                          ];
                                                                                                                                                                              const profileCompletion = Math.round(
                                                                                                                                                                                    (completionFields.filter(Boolean).length / completionFields.length) * 100
                                                                                                                                                                                        );

                                                                                                                                                                                            // Map dashboard form fields → Supabase column names
                                                                                                                                                                                                const candidateData = {
                                                                                                                                                                                                      clerk_user_id:      user.id,
                                                                                                                                                                                                            email,
                                                                                                                                                                                                                  full_name:          [user.firstName, user.lastName].filter(Boolean).join(' '),
                                                                                                                                                                                                                        job_title:          body.title         || null,
                                                                                                                                                                                                                              years_experience:   body.experience    || null,
                                                                                                                                                                                                                                    location:           body.location      || null,
                                                                                                                                                                                                                                          specialisms:        body.specialisms   || [],
                                                                                                                                                                                                                                                certifications:     body.certifications || [],
                                                                                                                                                                                                                                                      salary_amount:      body.salaryAmount  || null,
                                                                                                                                                                                                                                                            salary_currency:    body.salaryCurrency || 'GBP',
                                                                                                                                                                                                                                                                  salary_period:      body.salaryPeriod  || 'Year',
                                                                                                                                                                                                                                                                        work_preference:    body.workPreference || 'Both',
                                                                                                                                                                                                                                                                              bio:                body.bio           || null,
                                                                                                                                                                                                                                                                                    current_company:    body.currentCompany  || null,
                                                                                                                                                                                                                                                                                          previous_company:   body.previousCompany || null,
                                                                                                                                                                                                                                                                                                education:          body.education     || null,
                                                                                                                                                                                                                                                                                                      is_visible:         body.isVisible ?? true,
                                                                                                                                                                                                                                                                                                            profile_completion: profileCompletion,
                                                                                                                                                                                                                                                                                                                  updated_at:         new Date().toISOString(),
                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                          // Upsert — insert on first save, update on subsequent saves
                                                                                                                                                                                                                                                                                                                              const { data, error } = await supabaseAdmin
                                                                                                                                                                                                                                                                                                                                    .from('candidates')
                                                                                                                                                                                                                                                                                                                                          .upsert(candidateData, {
                                                                                                                                                                                                                                                                                                                                                  onConflict: 'clerk_user_id',
                                                                                                                                                                                                                                                                                                                                                          ignoreDuplicates: false,
                                                                                                                                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                                                                                                                                      .select()
                                                                                                                                                                                                                                                                                                                                                                            .single();

                                                                                                                                                                                                                                                                                                                                                                                if (error) {
                                                                                                                                                                                                                                                                                                                                                                                      console.error('Supabase upsert error:', error);
                                                                                                                                                                                                                                                                                                                                                                                            return NextResponse.json({ error: error.message }, { status: 500 });
                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                    return NextResponse.json({ success: true, candidate: data });
                                                                                                                                                                                                                                                                                                                                                                                                      } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                          console.error('Profile POST error:', err);
                                                                                                                                                                                                                                                                                                                                                                                                              return NextResponse.json({ error: String(err) }, { status: 500 });
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                // ─── PATCH /api/candidate/profile ─────────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                                // Immediately update a single field — used by the visibility toggle
                                                                                                                                                                                                                                                                                                                                                                                                                export async function PATCH(req: NextRequest) {
                                                                                                                                                                                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                                                                                                                                                                                      const user = await currentUser();
                                                                                                                                                                                                                                                                                                                                                                                                                          if (!user) {
                                                                                                                                                                                                                                                                                                                                                                                                                                return NextResponse.json({ error: 'Unauthorised' }, { status: 401 });
                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                        const body = await req.json();

                                                                                                                                                                                                                                                                                                                                                                                                                                            const { error } = await supabaseAdmin
                                                                                                                                                                                                                                                                                                                                                                                                                                                  .from('candidates')
                                                                                                                                                                                                                                                                                                                                                                                                                                                        .update({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                is_visible: body.isVisible,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        updated_at: new Date().toISOString(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .eq('clerk_user_id', user.id);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.error('Supabase PATCH error:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return NextResponse.json({ error: error.message }, { status: 500 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return NextResponse.json({ success: true });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.error('Profile PATCH error:', err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return NextResponse.json({ error: String(err) }, { status: 500 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }